# CMake generated Testfile for 
# Source directory: /home/lau/cmake-2.8.10.2/Tests/RunCMake
# Build directory: /home/lau/cmake-2.8.10.2/Tests/RunCMake
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(RunCMake.GeneratorExpression "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/GeneratorExpression" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/GeneratorExpression" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/GeneratorExpression/RunCMakeTest.cmake")
ADD_TEST(RunCMake.TargetPropertyGeneratorExpressions "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/TargetPropertyGeneratorExpressions" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/TargetPropertyGeneratorExpressions" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/TargetPropertyGeneratorExpressions/RunCMakeTest.cmake")
ADD_TEST(RunCMake.Languages "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/Languages" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/Languages" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/Languages/RunCMakeTest.cmake")
ADD_TEST(RunCMake.ObjectLibrary "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/ObjectLibrary" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/ObjectLibrary" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/ObjectLibrary/RunCMakeTest.cmake")
ADD_TEST(RunCMake.build_command "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/build_command" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/build_command" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/build_command/RunCMakeTest.cmake")
ADD_TEST(RunCMake.find_package "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/find_package" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/find_package" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/find_package/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/include" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/include" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/include/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include_directories "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/include_directories" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/include_directories" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/include_directories/RunCMakeTest.cmake")
ADD_TEST(RunCMake.list "/home/lau/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/lau/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/list" "-DRunCMake_BINARY_DIR=/home/lau/cmake-2.8.10.2/Tests/RunCMake/list" "-P" "/home/lau/cmake-2.8.10.2/Tests/RunCMake/list/RunCMakeTest.cmake")
